# Generated by Django 5.0.6 on 2024-05-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reminder',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
